### ISSUE TITLE
Style: AOE icons overlap with other elemens

### ISSUE THREAD

**Issue by GinoGalotti** [johreh/gloomycompanion#14]
Win demon 37 initiative has overlapping AOE skill (wasn't like that in my branch, so I assume it's about the new css layout). It's the only one with 2 AOE icons.

(the other icons look DOPE with this new css)

**Comment by GinoGalotti** [comment]
On cards like Deep terror (60) the AOE overlaps with "Pierce". 

![image](https://cloud.githubusercontent.com/assets/14745341/23616825/4cdfc88a-028b-11e7-9192-e53c851d9cd0.png)

This will be fixed if the CSS changes are rollbacked, but icons will look less cooler

**Comment by johreh** [comment]
Whoops, thought I already fixed that one at least. Fix uploaded.

**Comment by GinoGalotti** [comment]
Still happening on Wind Demon (2 AOEs in the same image overlapping)
